// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to add a message to the queue.
 */
export type AddQueuedMessageRequest = { content: string, variant: string | null, };
