// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A queued message waiting to be sent to an execution process.
 */
export type QueuedMessage = { id: string, task_attempt_id: string, content: string, variant: string | null, position: number, created_at: string, };
