// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a queued message.
 */
export type UpdateQueuedMessageRequest = { content: string | null, variant: string | null, };
