// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type FileContentResponse = { 
/**
 * The file path (relative if within a base directory)
 */
path: string, 
/**
 * The file content as text
 */
content: string, 
/**
 * File size in bytes
 */
size_bytes: bigint, 
/**
 * Whether the content was truncated due to size limit
 */
truncated: boolean, 
/**
 * Detected language based on file extension
 */
language: string | null, };

export type Project = { id: string, name: string, git_repo_path: string, setup_script: string | null, dev_script: string | null, cleanup_script: string | null, copy_files: string | null, 
/**
 * When true, setup script runs concurrently with the coding agent
 */
parallel_setup_script: boolean, remote_project_id: string | null, created_at: Date, updated_at: Date, is_remote: boolean, source_node_id: string | null, source_node_name: string | null, source_node_public_url: string | null, source_node_status: string | null, remote_last_synced_at: Date | null, 
/**
 * JSON array of default validation steps for new tasks in this project
 */
default_validation_steps: string | null, };

export type CreateProject = { name: string, git_repo_path: string, use_existing_repo: boolean, setup_script: string | null, dev_script: string | null, cleanup_script: string | null, copy_files: string | null, };

export type UpdateProject = { name: string | null, git_repo_path: string | null, setup_script: string | null, dev_script: string | null, cleanup_script: string | null, copy_files: string | null, parallel_setup_script: boolean | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type ProjectConfigSuggestion = { field: ProjectConfigField, value: string, confidence: ConfidenceLevel, source: string, };

export type ProjectConfigField = "SetupScript" | "DevScript" | "CleanupScript" | "CopyFiles" | "DevHost" | "DevPort";

export type ConfidenceLevel = "High" | "Medium";

export type ScanConfigRequest = { repo_path: string, };

export type ScanConfigResponse = { suggestions: Array<ProjectConfigSuggestion>, };

export type CreateRemoteProjectRequest = { organization_id: string, name: string, };

export type LinkToExistingRequest = { remote_project_id: string, };

export type LinkToLocalFolderRequest = { 
/**
 * The remote project ID to link to (from the Hive)
 */
remote_project_id: string, 
/**
 * The local folder path where the project will be created
 */
local_folder_path: string, 
/**
 * Optional project name (defaults to folder name if not provided)
 */
project_name: string | null, };

export type UnifiedProject = { "type": "local" } & Project | { "type": "remote" } & RemoteNodeProject;

export type RemoteNodeProject = { 
/**
 * Local ID in the unified projects table
 */
id: string, 
/**
 * ID of the node this project belongs to
 */
node_id: string, 
/**
 * Remote project ID from the Hive
 */
project_id: string, project_name: string, git_repo_path: string, last_synced_at: Date | null, created_at: Date, node_name: string, node_status: CachedNodeStatus, node_public_url: string | null, };

export type UnifiedProjectsResponse = { 
/**
 * Local projects (always shown first)
 */
local: Array<Project>, 
/**
 * Projects from other nodes grouped by node
 */
remote_by_node: Array<RemoteNodeGroup>, };

export type RemoteNodeGroup = { node_id: string, node_name: string, node_status: CachedNodeStatus, node_public_url: string | null, projects: Array<RemoteNodeProject>, };

export type MergedProject = { 
/**
 * Use local project ID if exists, otherwise first remote's ID
 */
id: string, name: string, git_repo_path: string, created_at: Date, 
/**
 * Linking status - Hive project ID (if linked)
 */
remote_project_id: string | null, 
/**
 * Location info - where the project runs
 */
has_local: boolean, 
/**
 * Local project ID if has_local is true
 */
local_project_id: string | null, 
/**
 * List of remote nodes that have this project
 */
nodes: Array<NodeLocation>, 
/**
 * For sorting - timestamp of last task attempt
 */
last_attempt_at: Date | null, };

export type NodeLocation = { node_id: string, 
/**
 * Full name like "tardis.raverx.net"
 */
node_name: string, 
/**
 * Truncated at first period: "tardis"
 */
node_short_name: string, node_status: CachedNodeStatus, node_public_url: string | null, 
/**
 * The project ID on that node
 */
remote_project_id: string, };

export type MergedProjectsResponse = { projects: Array<MergedProject>, };

export type CachedNodeStatus = "pending" | "online" | "offline" | "busy" | "draining";

export type CachedNodeCapabilities = { 
/**
 * List of executor types this node supports
 */
executors: Array<string>, 
/**
 * Maximum number of concurrent tasks
 */
max_concurrent_tasks: number, 
/**
 * Operating system (e.g., "darwin", "linux", "windows")
 */
os: string, 
/**
 * CPU architecture (e.g., "arm64", "x86_64")
 */
arch: string, 
/**
 * Vibe Kanban version running on the node
 */
version: string, };

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest;

export type ScriptContext = "SetupScript" | "CleanupScript" | "DevServer" | "ToolInstallScript";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", OPENCODE = "OPENCODE", CURSOR_AGENT = "CURSOR_AGENT", QWEN_CODE = "QWEN_CODE", COPILOT = "COPILOT", DROID = "DROID" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type TagSearchParams = { search: string | null, };

export type TaskVariable = { id: string, task_id: string, name: string, value: string, created_at: string, updated_at: string, };

export type CreateTaskVariable = { name: string, value: string, };

export type UpdateTaskVariable = { name: string | null, value: string | null, };

export type ResolvedVariable = { name: string, value: string, 
/**
 * The task ID this variable was defined on (may differ from requested task_id for inherited vars)
 */
source_task_id: string, 
/**
 * True if this variable was inherited from a parent task
 */
inherited: boolean, };

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";

export type Task = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, parent_task_id: string | null, shared_task_id: string | null, created_at: string, updated_at: string, is_remote: boolean, remote_assignee_user_id: string | null, remote_assignee_name: string | null, remote_assignee_username: string | null, remote_version: bigint, remote_last_synced_at: string | null, remote_stream_node_id: string | null, remote_stream_url: string | null, 
/**
 * JSON array of validation step strings, e.g. ["Run tests", "Check E2E in browser"]
 */
validation_steps: string | null, 
/**
 * Timestamp when task was archived. NULL means not archived.
 */
archived_at: Date | null, 
/**
 * Timestamp of last significant activity (status change, execution start).
 * Unlike updated_at, this is NOT updated for metadata changes like title/description edits.
 */
activity_at: Date | null, };

export type TaskWithAttemptStatus = { has_in_progress_attempt: boolean, has_merged_attempt: boolean, last_attempt_failed: boolean, executor: string, id: string, project_id: string, title: string, description: string | null, status: TaskStatus, parent_task_id: string | null, shared_task_id: string | null, created_at: string, updated_at: string, is_remote: boolean, remote_assignee_user_id: string | null, remote_assignee_name: string | null, remote_assignee_username: string | null, remote_version: bigint, remote_last_synced_at: string | null, remote_stream_node_id: string | null, remote_stream_url: string | null, 
/**
 * JSON array of validation step strings, e.g. ["Run tests", "Check E2E in browser"]
 */
validation_steps: string | null, 
/**
 * Timestamp when task was archived. NULL means not archived.
 */
archived_at: Date | null, 
/**
 * Timestamp of last significant activity (status change, execution start).
 * Unlike updated_at, this is NOT updated for metadata changes like title/description edits.
 */
activity_at: Date | null, };

export type TaskRelationships = { parent_task: Task | null, current_attempt: TaskAttempt, children: Array<Task>, };

export type TaskWithProjectInfo = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, parent_task_id: string | null, shared_task_id: string | null, created_at: string, updated_at: string, is_remote: boolean, remote_assignee_user_id: string | null, remote_assignee_name: string | null, remote_assignee_username: string | null, remote_version: bigint, remote_last_synced_at: string | null, remote_stream_node_id: string | null, remote_stream_url: string | null, archived_at: Date | null, assignee_first_name: string | null, assignee_last_name: string | null, assignee_username: string | null, has_in_progress_attempt: boolean, has_merged_attempt: boolean, last_attempt_failed: boolean, executor: string, project_name: string, source_node_name: string | null, };

export type AllTasksResponse = { tasks: Array<TaskWithProjectInfo>, };

export type DashboardTask = { task_id: string, task_title: string, project_id: string, project_name: string, status: TaskStatus, executor: string, updated_at: string, };

export type DashboardSummary = { running_tasks: Array<DashboardTask>, in_review_tasks: Array<DashboardTask>, };

export type ActivityCategory = "needs_review" | "in_progress" | "completed";

export type ActivityFeedItem = { task_id: string, task_title: string, project_id: string, project_name: string, status: TaskStatus, category: ActivityCategory, executor: string, activity_at: string, 
/**
 * Whether this item has been dismissed by the user.
 */
is_dismissed: boolean, };

export type ActivityCounts = { needs_review: number, in_progress: number, completed: number, 
/**
 * Number of dismissed items (across all categories).
 */
dismissed: number, };

export type ActivityFeed = { items: Array<ActivityFeedItem>, counts: ActivityCounts, };

export type CreateTask = { project_id: string, title: string, description: string | null, status: TaskStatus | null, parent_task_id: string | null, image_ids: Array<string> | null, shared_task_id: string | null, validation_steps: string | null, };

export type UpdateTask = { title: string | null, description: string | null, status: TaskStatus | null, parent_task_id: string | null, image_ids: Array<string> | null, validation_steps: string | null, };

export type SharedTask = { id: string, remote_project_id: string, title: string, description: string | null, status: TaskStatus, assignee_user_id: string | null, assignee_first_name: string | null, assignee_last_name: string | null, assignee_username: string | null, version: bigint, last_event_seq: bigint | null, created_at: Date, updated_at: Date, activity_at: Date | null, };

export type Image = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type CreateImage = { file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, };

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type LoginStatus = { "status": "loggedout" } | { "status": "loggedin", profile: ProfileResponse, };

export type ProfileResponse = { user_id: string, username: string | null, email: string, providers: Array<ProviderProfile>, };

export type ProviderProfile = { provider: string, username: string | null, display_name: string | null, email: string | null, avatar_url: string | null, };

export type StatusResponse = { logged_in: boolean, profile: ProfileResponse | null, degraded: boolean | null, };

export enum MemberRole { ADMIN = "ADMIN", MEMBER = "MEMBER" }

export enum InvitationStatus { PENDING = "PENDING", ACCEPTED = "ACCEPTED", DECLINED = "DECLINED", EXPIRED = "EXPIRED" }

export type Organization = { id: string, name: string, slug: string, is_personal: boolean, created_at: string, updated_at: string, };

export type OrganizationWithRole = { id: string, name: string, slug: string, is_personal: boolean, created_at: string, updated_at: string, user_role: MemberRole, };

export type ListOrganizationsResponse = { organizations: Array<OrganizationWithRole>, };

export type GetOrganizationResponse = { organization: Organization, user_role: string, };

export type CreateOrganizationRequest = { name: string, slug: string, };

export type CreateOrganizationResponse = { organization: OrganizationWithRole, };

export type UpdateOrganizationRequest = { name: string, };

export type Invitation = { id: string, organization_id: string, invited_by_user_id: string | null, email: string, role: MemberRole, status: InvitationStatus, token: string, created_at: string, expires_at: string, };

export type CreateInvitationRequest = { email: string, role: MemberRole, };

export type CreateInvitationResponse = { invitation: Invitation, };

export type ListInvitationsResponse = { invitations: Array<Invitation>, };

export type GetInvitationResponse = { id: string, organization_slug: string, role: MemberRole, expires_at: string, };

export type AcceptInvitationResponse = { organization_id: string, organization_slug: string, role: MemberRole, };

export type RevokeInvitationRequest = { invitation_id: string, };

export type OrganizationMember = { user_id: string, role: MemberRole, joined_at: string, };

export type OrganizationMemberWithProfile = { user_id: string, role: MemberRole, joined_at: string, first_name: string | null, last_name: string | null, username: string | null, email: string | null, avatar_url: string | null, };

export type ListMembersResponse = { members: Array<OrganizationMemberWithProfile>, };

export type UpdateMemberRoleRequest = { role: MemberRole, };

export type UpdateMemberRoleResponse = { user_id: string, role: MemberRole, };

export type RemoteProject = { id: string, organization_id: string, name: string, metadata: Record<string, unknown>, created_at: string, };

export type ListProjectsResponse = { projects: Array<RemoteProject>, };

export type RemoteProjectMembersResponse = { organization_id: string, members: Array<OrganizationMemberWithProfile>, };

export type UserSystemInfo = { config: Config, analytics_user_id: string, login_status: LoginStatus, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, is_dev_mode: boolean, hostname: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CreateFollowUpAttempt = { prompt: string, variant: string | null, image_ids: Array<string> | null, retry_process_id: string | null, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type DraftResponse = { task_attempt_id: string, draft_type: DraftType, retry_process_id: string | null, prompt: string, queued: boolean, variant: string | null, image_ids: Array<string> | null, version: bigint, };

export type UpdateFollowUpDraftRequest = { prompt: string | null, variant: string | null | null, image_ids: Array<string> | null, version: bigint | null, };

export type UpdateRetryFollowUpDraftRequest = { retry_process_id: string, prompt: string | null, variant: string | null | null, image_ids: Array<string> | null, version: bigint | null, };

export type ChangeTargetBranchRequest = { new_target_branch: string, };

export type ChangeTargetBranchResponse = { new_target_branch: string, status: [number, number], };

export type RenameBranchRequest = { new_branch_name: string, };

export type RenameBranchResponse = { branch: string, };

export type CommitCompareResult = { head_oid: string, target_oid: string, ahead_from_head: number, behind_from_head: number, is_linear: boolean, };

export type OpenEditorRequest = { editor_type: string | null, file_path: string | null, };

export type OpenEditorResponse = { url: string | null, };

export type AssignSharedTaskRequest = { new_assignee_user_id: string | null, version: bigint | null, };

export type AssignSharedTaskResponse = { shared_task: SharedTask, };

export type ShareTaskResponse = { shared_task_id: string, };

export type CreateAndStartTaskRequest = { task: CreateTask, executor_profile_id: ExecutorProfileId, base_branch: string, };

export type ArchiveTaskRequest = { 
/**
 * Whether to also archive subtasks (children). Defaults to true.
 */
include_subtasks: boolean, };

export type ArchiveTaskResponse = { 
/**
 * The archived/unarchived task
 */
task: Task, 
/**
 * Number of subtasks also archived (only for archive operation)
 */
subtasks_archived: bigint, };

export type PreviewExpansionRequest = { 
/**
 * The text to expand variables in
 */
text: string, };

export type PreviewExpansionResponse = { 
/**
 * The text with variables expanded
 */
expanded_text: string, 
/**
 * Variables that were referenced but not defined
 */
undefined_variables: Array<string>, 
/**
 * Variables that were successfully expanded
 */
expanded_variables: Array<ExpandedVariableInfo>, };

export type ExpandedVariableInfo = { 
/**
 * The variable name
 */
name: string, 
/**
 * The task ID where this variable was defined
 */
source_task_id: string | null, };

export type CreateGitHubPrRequest = { title: string, body: string | null, target_branch: string | null, };

export type ImageResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, 
/**
 * Deprecated: analytics has been removed. Field kept for config compatibility.
 */
analytics_enabled: boolean, 
/**
 * Deprecated: Sentry error reporting has been removed. Field kept for config compatibility.
 */
sentry_enabled: boolean, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, dev_banner: DevBannerConfig, 
/**
 * Pagination settings for log display
 */
pagination: PaginationConfig, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, };

export enum EditorType { VS_CODE = "VS_CODE", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "JA" | "ES" | "KO";

export type DevBannerConfig = { 
/**
 * Custom background color (CSS color string), None = default orange
 */
background_color: string | null, 
/**
 * Custom foreground/text color (CSS color string), None = default white
 */
foreground_color: string | null, 
/**
 * Whether to display the system hostname in the banner
 */
show_hostname: boolean, 
/**
 * Whether to display the OS type and version in the banner
 */
show_os_info: boolean, };

export type PaginationConfig = { 
/**
 * Number of log entries to load initially (default: 100)
 */
initial_load: bigint, 
/**
 * Maximum entries per page request (default: 500)
 */
max_limit: bigint, };

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@latest")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorConfig = { [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } };

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorConfig }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER" }

export type ClaudeCode = { append_prompt: AppendPrompt, no_context?: boolean | null, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, 
/**
 * Enable interactive question UI for AskUserQuestion control requests.
 * When enabled, questions are displayed as clickable options in the UI.
 * When disabled, questions fall back to text-based prompts.
 * Defaults to true.
 */
interactive_questions?: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Gemini = { append_prompt: AppendPrompt, no_context?: boolean | null, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Amp = { append_prompt: AppendPrompt, no_context?: boolean | null, dangerously_allow_all?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Codex = { append_prompt: AppendPrompt, no_context?: boolean | null, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-failure" | "on-request" | "never";

export type ReasoningEffort = "low" | "medium" | "high" | "xhigh";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type CursorAgent = { append_prompt: AppendPrompt, no_context?: boolean | null, force?: boolean | null, model?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Copilot = { append_prompt: AppendPrompt, no_context?: boolean | null, model?: string | null, allow_all_tools?: boolean | null, allow_tool?: string | null, deny_tool?: string | null, add_dir?: Array<string> | null, disable_mcp_server?: Array<string> | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Opencode = { append_prompt: AppendPrompt, no_context?: boolean | null, model?: string | null, agent?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type QwenCode = { append_prompt: AppendPrompt, no_context?: boolean | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Droid = { append_prompt: AppendPrompt, no_context?: boolean | null, autonomy: Autonomy, model?: string | null, reasoning_effort?: DroidReasoningEffort | null, base_command_override?: string | null, additional_params?: Array<string> | null, };

export type Autonomy = "normal" | "low" | "medium" | "high" | "skip-permissions-unsafe";

export type DroidReasoningEffort = "none" | "dynamic" | "off" | "low" | "medium" | "high";

export type AppendPrompt = string | null;

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, };

export type CreateTaskAttemptBody = { task_id: string, 
/**
 * Executor profile specification
 */
executor_profile_id: ExecutorProfileId, base_branch: string, 
/**
 * Target node ID for remote execution (if project exists on multiple nodes).
 * When set, the request will be proxied to the specified node.
 */
target_node_id: string | null, };

export type RunAgentSetupRequest = { executor_profile_id: ExecutorProfileId, };

export type RunAgentSetupResponse = Record<string, never>;

export type GhCliSetupError = "BREW_MISSING" | "SETUP_HELPER_NOT_SUPPORTED" | { "OTHER": { message: string, } };

export type RebaseTaskAttemptRequest = { old_base_branch: string | null, new_base_branch: string | null, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, } | { "type": "rebase_in_progress" };

export type PushError = { "type": "force_push_required" };

export type CreatePrError = { "type": "github_cli_not_installed" } | { "type": "github_cli_not_logged_in" } | { "type": "git_cli_not_logged_in" } | { "type": "git_cli_not_installed" } | { "type": "target_branch_not_found", branch: string, };

export type CommitInfo = { sha: string, subject: string, };

export type BranchStatus = { commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, 
/**
 * True if a `git rebase` is currently in progress in this worktree
 */
is_rebase_in_progress: boolean, 
/**
 * Current conflict operation if any
 */
conflict_op: ConflictOp | null, 
/**
 * List of files currently in conflicted (unmerged) state
 */
conflicted_files: Array<string>, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type TaskAttempt = { id: string, task_id: string, container_ref: string | null, branch: string, target_branch: string, executor: string, worktree_deleted: boolean, setup_completed_at: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, task_attempt_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, 
/**
 * Git HEAD commit OID captured before the process starts
 */
before_head_commit: string | null, 
/**
 * Git HEAD commit OID captured after the process ends
 */
after_head_commit: string | null, status: ExecutionProcessStatus, exit_code: bigint | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, 
/**
 * System process ID (PID) for process tree discovery
 */
pid: bigint | null, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "codingagent" | "devserver";

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, task_attempt_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, task_attempt_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type Draft = { id: string, task_attempt_id: string, draft_type: DraftType, retry_process_id: string | null, prompt: string, queued: boolean, sending: boolean, variant: string | null, image_ids: Array<string> | null, created_at: string, updated_at: string, version: bigint, };

export type DraftType = "follow_up" | "retry";

export type BackupInfo = { 
/**
 * Filename of the backup (e.g., "db_backup_20250101_100000.sqlite")
 */
filename: string, 
/**
 * When the backup was created
 */
created_at: Date, 
/**
 * Size of the backup file in bytes
 */
size_bytes: bigint, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "other", description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, requested_at: string, timeout_at: string, } | { "status": "timed_out" } | { "status": "pending_question", question_id: string, questions: Array<Question>, requested_at: string, timeout_at: string, };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type CreateApprovalRequest = { tool_name: string, tool_input: JsonValue, tool_call_id: string, };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalStatus, 
/**
 * Optional answers for AskUserQuestion responses (header -> answer)
 */
answers?: { [key in string]?: string }, };

export type Question = { question: string, header: string, multiSelect: boolean, options: Array<QuestionOption>, };

export type QuestionOption = { label: string, description: string, };

export type OutputType = "stdout" | "stderr" | "system" | "json_patch" | "session_id" | "finished" | "refresh_required";

export type LogEntry = { 
/**
 * Sequential ID for cursor-based pagination.
 */
id: bigint, 
/**
 * The content of the log entry.
 */
content: string, 
/**
 * The type of output (stdout, stderr, system, json_patch, etc.).
 */
output_type: OutputType, 
/**
 * When the log entry was created.
 */
timestamp: string, 
/**
 * The execution ID this log belongs to.
 */
execution_id: string, };

export type PaginatedLogs = { 
/**
 * The log entries for this page.
 */
entries: Array<LogEntry>, 
/**
 * Cursor for the next page (if more entries exist).
 */
next_cursor: bigint | null, 
/**
 * Whether there are more entries after this page.
 */
has_more: boolean, 
/**
 * Total count of log entries (if available).
 */
total_count: bigint | null, };

export type Direction = "forward" | "backward";

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type ProcessInfo = { 
/**
 * System process ID
 */
pid: number, 
/**
 * Parent process ID (None for orphans/init)
 */
parent_pid: number | null, 
/**
 * Process name (executable name)
 */
name: string, 
/**
 * Full command line arguments
 */
command: Array<string>, 
/**
 * Working directory of the process
 */
working_directory: string | null, 
/**
 * Memory usage in bytes
 */
memory_bytes: bigint, 
/**
 * CPU usage percentage (0.0 - 100.0)
 */
cpu_percent: number, 
/**
 * ID of the execution process record (if this is a tracked executor)
 */
execution_process_id: string | null, 
/**
 * ID of the task attempt this process belongs to
 */
task_attempt_id: string | null, 
/**
 * ID of the task this process belongs to
 */
task_id: string | null, 
/**
 * ID of the project this process belongs to
 */
project_id: string | null, 
/**
 * Name of the project (for display)
 */
project_name: string | null, 
/**
 * Title of the task (for display)
 */
task_title: string | null, 
/**
 * Whether this is a direct executor process (vs a child spawned by an executor)
 */
is_executor: boolean, };

export type ProcessFilter = { 
/**
 * Filter by project ID
 */
project_id: string | null, 
/**
 * Filter by task ID
 */
task_id: string | null, 
/**
 * Filter by task attempt ID
 */
task_attempt_id: string | null, 
/**
 * Only include executor processes (exclude children)
 */
executors_only: boolean, };

export type KillScope = { "type": "single", pid: number, } | { "type": "task", task_id: string, } | { "type": "project", project_id: string, } | { "type": "all_except_executors" } | { "type": "all" };

export type KillResult = { 
/**
 * Number of processes successfully killed
 */
killed_count: number, 
/**
 * Number of processes that failed to kill
 */
failed_count: number, 
/**
 * PIDs that failed to kill with error messages
 */
failures: Array<KillFailure>, };

export type KillFailure = { 
/**
 * PID that failed to kill
 */
pid: number, 
/**
 * Error message
 */
error: string, };