#!/bin/bash
#
# Development Swarm Setup Script
#
# This script helps configure a local swarm/hive development environment for testing
# remote task operations.
#
# Port Assignments:
#   - Hive: 4000
#   - Frontend: 4001
#   - Backend (Node): 4002
#
# Prerequisites:
#   1. PostgreSQL running locally or Docker installed
#   2. GitHub OAuth App credentials (create at https://github.com/settings/developers)
#   3. Google OAuth credentials (optional, create at https://console.cloud.google.com)
#
# Usage:
#   ./scripts/dev-swarm-setup.sh           # Interactive setup
#   ./scripts/dev-swarm-setup.sh --check   # Check prerequisites
#   ./scripts/dev-swarm-setup.sh --start   # Start all services (after setup)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Port configuration
HIVE_PORT=4000
FRONTEND_PORT=4001
BACKEND_PORT=4002

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}\n"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

check_prerequisites() {
    print_header "Checking Prerequisites"

    local all_ok=true

    # Check PostgreSQL
    if pg_isready &>/dev/null; then
        print_success "PostgreSQL is running"
    elif command -v docker &>/dev/null; then
        print_warning "PostgreSQL not running locally, but Docker is available"
        print_info "Docker will be used for the database"
    else
        print_error "PostgreSQL not running and Docker not available"
        print_info "Install PostgreSQL or Docker to proceed"
        all_ok=false
    fi

    # Check if ports are available
    for port in $HIVE_PORT $FRONTEND_PORT $BACKEND_PORT; do
        if lsof -i:$port &>/dev/null; then
            print_error "Port $port is already in use"
            all_ok=false
        else
            print_success "Port $port is available"
        fi
    done

    # Check for cargo
    if command -v cargo &>/dev/null; then
        print_success "Cargo is installed"
    else
        print_error "Cargo not found - required to build the hive server"
        all_ok=false
    fi

    # Check for pnpm/npm
    if command -v pnpm &>/dev/null; then
        print_success "pnpm is installed"
    elif command -v npm &>/dev/null; then
        print_warning "pnpm not found, will use npm instead"
    else
        print_error "Neither pnpm nor npm found"
        all_ok=false
    fi

    # Check env file
    local env_file="$PROJECT_ROOT/crates/remote/.env.remote"
    if [ -f "$env_file" ]; then
        # Check for placeholder OAuth values
        if grep -q "your_github_client_id" "$env_file"; then
            print_warning ".env.remote exists but OAuth credentials not configured"
            print_info "You'll need to add your GitHub/Google OAuth credentials"
        else
            print_success ".env.remote is configured"
        fi
    else
        print_warning ".env.remote not found - will create during setup"
    fi

    echo ""
    if [ "$all_ok" = true ]; then
        print_success "All prerequisites met!"
        return 0
    else
        print_error "Some prerequisites are missing"
        return 1
    fi
}

create_env_file() {
    print_header "Creating Environment Configuration"

    local env_file="$PROJECT_ROOT/crates/remote/.env.remote.dev"

    # Generate JWT secret
    local jwt_secret
    jwt_secret=$(openssl rand -base64 32)

    cat > "$env_file" << EOF
# Development Swarm Environment Configuration
# Generated by dev-swarm-setup.sh
# Ports: Hive=$HIVE_PORT, Frontend=$FRONTEND_PORT, Backend=$BACKEND_PORT

# =============================================================================
# Network Configuration
# =============================================================================
SERVER_LISTEN_ADDR=0.0.0.0:$HIVE_PORT
SERVER_PUBLIC_BASE_URL=http://localhost:$HIVE_PORT

# =============================================================================
# Database
# =============================================================================
# For local PostgreSQL:
SERVER_DATABASE_URL=postgres://postgres:postgres@localhost:5432/vibe_remote_dev

# =============================================================================
# GitHub OAuth (Required)
# =============================================================================
# Create an OAuth App at: https://github.com/settings/developers
# Homepage URL: http://localhost:$HIVE_PORT
# Callback URL: http://localhost:$HIVE_PORT/v1/oauth/github/callback

GITHUB_OAUTH_CLIENT_ID=your_github_client_id
GITHUB_OAUTH_CLIENT_SECRET=your_github_client_secret

# =============================================================================
# Google OAuth (Optional)
# =============================================================================
# Create OAuth credentials at: https://console.cloud.google.com/apis/credentials
# Callback URL: http://localhost:$HIVE_PORT/v1/oauth/google/callback

GOOGLE_OAUTH_CLIENT_ID=your_google_client_id
GOOGLE_OAUTH_CLIENT_SECRET=your_google_client_secret

# =============================================================================
# Security
# =============================================================================
VIBEKANBAN_REMOTE_JWT_SECRET=$jwt_secret

# =============================================================================
# Email (can be empty for development)
# =============================================================================
LOOPS_EMAIL_API_KEY=
EOF

    print_success "Created $env_file"
    print_info "JWT secret generated: ${jwt_secret:0:20}..."
    echo ""
    print_warning "IMPORTANT: Edit $env_file and add your OAuth credentials:"
    echo "  1. Go to https://github.com/settings/developers"
    echo "  2. Create a new OAuth App"
    echo "  3. Set Homepage URL to: http://localhost:$HIVE_PORT"
    echo "  4. Set Callback URL to: http://localhost:$HIVE_PORT/v1/oauth/github/callback"
    echo "  5. Copy Client ID and Client Secret to .env.remote.dev"
}

create_database() {
    print_header "Setting Up Database"

    if pg_isready &>/dev/null; then
        print_info "Creating database 'vibe_remote_dev'..."
        if psql -c "CREATE DATABASE vibe_remote_dev;" 2>/dev/null; then
            print_success "Database created"
        else
            print_warning "Database may already exist (this is okay)"
        fi
    else
        print_warning "PostgreSQL not accessible - please create the database manually"
        print_info "Run: createdb vibe_remote_dev"
    fi
}

create_node_env() {
    print_header "Creating Node Configuration"

    local env_file="$PROJECT_ROOT/.env.swarm-node"
    local jwt_secret

    # Read JWT secret from hive env
    local hive_env="$PROJECT_ROOT/crates/remote/.env.remote.dev"
    if [ -f "$hive_env" ]; then
        jwt_secret=$(grep VIBEKANBAN_REMOTE_JWT_SECRET "$hive_env" | cut -d= -f2)
    else
        jwt_secret=$(openssl rand -base64 32)
    fi

    cat > "$env_file" << EOF
# Node Configuration for Swarm Development
# Generated by dev-swarm-setup.sh
#
# Start the node with: source .env.swarm-node && pnpm run dev

# Connect to hive
VK_HIVE_URL=ws://localhost:$HIVE_PORT
VK_NODE_API_KEY=<your-api-key-here>
VK_NODE_NAME="Dev Node"

# Direct streaming support
VK_NODE_PUBLIC_URL=http://localhost:$BACKEND_PORT
VK_CONNECTION_TOKEN_SECRET=$jwt_secret

# Port configuration
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
HOST=0.0.0.0
EOF

    print_success "Created $env_file"
    print_info ""
    print_warning "After starting the hive and authenticating, you'll need to:"
    echo "  1. Create a node API key via the hive API"
    echo "  2. Update VK_NODE_API_KEY in $env_file"
}

print_start_instructions() {
    print_header "Setup Complete - Start Instructions"

    echo "To start the swarm development environment:"
    echo ""
    echo -e "${YELLOW}1. Start the Hive (Terminal 1):${NC}"
    echo "   cd $PROJECT_ROOT/crates/remote"
    echo "   export \$(cat .env.remote.dev | grep -v '^#' | xargs)"
    echo "   cargo run"
    echo ""
    echo -e "${YELLOW}2. Authenticate with the Hive:${NC}"
    echo "   # Follow OAuth flow to get an access token"
    echo "   # Then create a node API key:"
    echo "   curl -X POST http://localhost:$HIVE_PORT/v1/nodes/api-keys \\"
    echo '     -H "Authorization: Bearer <your-token>" \\'
    echo '     -H "Content-Type: application/json" \\'
    echo '     -d '"'"'{"organization_id": "<org-uuid>", "name": "Dev Node"}'"'"
    echo ""
    echo -e "${YELLOW}3. Start the Node (Terminal 2):${NC}"
    echo "   cd $PROJECT_ROOT"
    echo "   # Update VK_NODE_API_KEY in .env.swarm-node first!"
    echo "   source .env.swarm-node"
    echo "   BACKEND_PORT=$BACKEND_PORT FRONTEND_PORT=$FRONTEND_PORT pnpm run dev"
    echo ""
    echo -e "${YELLOW}4. Access the Application:${NC}"
    echo "   Frontend: http://localhost:$FRONTEND_PORT"
    echo "   Backend:  http://localhost:$BACKEND_PORT"
    echo "   Hive:     http://localhost:$HIVE_PORT"
    echo ""
    print_info "See docs/swarm-hive-setup.mdx for detailed instructions"
}

# Main
case "${1:-}" in
    --check)
        check_prerequisites
        ;;
    --start)
        print_error "Start functionality not yet implemented"
        print_info "Please follow the manual start instructions below"
        print_start_instructions
        ;;
    *)
        print_header "Vibe Kanban Swarm Development Setup"
        echo "This script configures a local swarm environment for testing."
        echo "Ports: Hive=$HIVE_PORT, Frontend=$FRONTEND_PORT, Backend=$BACKEND_PORT"
        echo ""

        check_prerequisites || true
        create_env_file
        create_database
        create_node_env
        print_start_instructions
        ;;
esac
