// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts per category for badge display.
 */
export type ActivityCounts = { needs_review: number, in_progress: number, completed: number, };
