// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a dismissed activity feed item.
 */
export type ActivityDismissal = { id: string, task_id: string, dismissed_at: string, };
