// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCounts } from "./ActivityCounts";
import type { ActivityFeedItem } from "./ActivityFeedItem";

/**
 * Activity feed response with items and counts.
 */
export type ActivityFeed = { items: Array<ActivityFeedItem>, counts: ActivityCounts, };
