// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCategory } from "./ActivityCategory";
import type { TaskStatus } from "./TaskStatus";

/**
 * A single activity feed item.
 */
export type ActivityFeedItem = { task_id: string, task_title: string, project_id: string, project_name: string, status: TaskStatus, category: ActivityCategory, executor: string, activity_at: string, };
