// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category for activity feed items.
 */
export type ActivityCategory = "needs_review" | "in_progress" | "completed";
