// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskWithProjectInfo } from "./TaskWithProjectInfo";

/**
 * Response for the all tasks endpoint
 */
export type AllTasksResponse = { tasks: Array<TaskWithProjectInfo>, };
