// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a database backup file.
 */
export type BackupInfo = { 
/**
 * Filename of the backup (e.g., "db_backup_20250101_100000.sqlite")
 */
filename: string, 
/**
 * When the backup was created
 */
created_at: Date, 
/**
 * Size of the backup file in bytes
 */
size_bytes: bigint, };
