// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

/**
 * A task summary for the dashboard view, containing essential info plus project context
 */
export type DashboardTask = { task_id: string, task_title: string, project_id: string, project_name: string, status: TaskStatus, executor: string, updated_at: string, };
