// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardTask } from "./DashboardTask";

/**
 * Summary of active tasks across all projects for dashboard display
 */
export type DashboardSummary = { running_tasks: Array<DashboardTask>, in_review_tasks: Array<DashboardTask>, };
