// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics about the SQLite database.
 */
export type DatabaseStats = { 
/**
 * Size of the main database file in bytes
 */
database_size_bytes: bigint, 
/**
 * Size of the WAL (Write-Ahead Log) file in bytes
 */
wal_size_bytes: bigint, 
/**
 * Number of free pages in the database (reclaimable with VACUUM)
 */
free_pages: bigint, 
/**
 * Size of each database page in bytes
 */
page_size: bigint, 
/**
 * Total number of tasks in the database
 */
task_count: bigint, 
/**
 * Total number of task attempts in the database
 */
task_attempt_count: bigint, 
/**
 * Total number of execution processes in the database
 */
execution_process_count: bigint, 
/**
 * Total number of log entries in the database
 */
log_entry_count: bigint, };
