// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single log entry stored in the database.
 *
 * This struct maps to the `log_entries` table and stores individual log messages
 * rather than batched JSONL. This design is required for ElectricSQL compatibility.
 */
export type DbLogEntry = { 
/**
 * Auto-incrementing primary key for cursor-based pagination.
 */
id: bigint, 
/**
 * The execution process this log belongs to.
 */
execution_id: string, 
/**
 * The type of output (stdout, stderr, system, etc.).
 */
output_type: string, 
/**
 * The content of the log message.
 */
content: string, 
/**
 * When this log entry was created.
 */
timestamp: string, };
