// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of all database metrics.
 */
export type DbMetricsSnapshot = { 
/**
 * Total number of queries executed.
 */
queries_total: bigint, 
/**
 * Number of slow queries (> threshold).
 */
queries_slow: bigint, 
/**
 * Average query duration in milliseconds.
 */
query_avg_duration_ms: number, 
/**
 * Total retry attempts due to SQLITE_BUSY.
 */
retry_attempts: bigint, 
/**
 * Retries that succeeded.
 */
retry_successes: bigint, 
/**
 * Retries that failed after all attempts.
 */
retry_failures: bigint, 
/**
 * SQLITE_BUSY errors encountered.
 */
busy_errors: bigint, 
/**
 * Other database errors.
 */
other_errors: bigint, 
/**
 * Total pool connection acquisitions.
 */
pool_acquires_total: bigint, 
/**
 * Pool acquisition timeouts.
 */
pool_timeouts: bigint, 
/**
 * Current WAL file size in bytes.
 */
wal_size_bytes: bigint, 
/**
 * Last checkpoint duration in milliseconds.
 */
last_checkpoint_duration_ms: bigint, 
/**
 * Estimated 50th percentile latency (ms).
 */
latency_p50_ms: bigint, 
/**
 * Estimated 95th percentile latency (ms).
 */
latency_p95_ms: bigint, 
/**
 * Estimated 99th percentile latency (ms).
 */
latency_p99_ms: bigint, };
