// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbLogEntry } from "./DbLogEntry";

/**
 * Paginated result for log entry queries.
 */
export type PaginatedDbLogEntries = { 
/**
 * The log entries for this page.
 */
entries: Array<DbLogEntry>, 
/**
 * Cursor for the next page (if more entries exist).
 */
next_cursor: bigint | null, 
/**
 * Whether there are more entries after this page.
 */
has_more: boolean, 
/**
 * Total count of log entries (if available).
 */
total_count: bigint | null, };
