// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection pool statistics.
 */
export type PoolStats = { 
/**
 * Total connections in the pool.
 */
size: number, 
/**
 * Idle connections available.
 */
idle: number, 
/**
 * Currently acquired connections.
 */
acquired: number, };
