// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified template combining system, swarm, and local sources
 */
export type UnifiedTemplate = { id: string, name: string, content: string, description: string | null, 
/**
 * Source of the template: "system", "swarm", or "local"
 */
source: string, created_at: Date | null, updated_at: Date | null, };
