// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a VACUUM operation.
 */
export type VacuumResult = { 
/**
 * Database size before VACUUM in bytes
 */
size_before_bytes: bigint, 
/**
 * Database size after VACUUM in bytes
 */
size_after_bytes: bigint, 
/**
 * Bytes freed by the VACUUM operation
 */
freed_bytes: bigint, };
